name: Deploy to GitHub Pages

# on:
#   push:
#     branches: [ master ]
on:
  workflow_dispatch:  # 手动触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7

      - name: Setup Node.js 🔧
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: './doc/package-lock.json'

      - name: Build 🏗️
        run: |
          cd doc
          npm install
          npm run docs:build

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/.vitepress/dist
          # 可选：自定义域名
          # cname: your-domain.com
